### ISSUE TITLE
How-Do-I page template not excluding "Uncategorised" due to US spelling with a "z"

### ISSUE THREAD

**Issue by nmcgann** [helpful/govintranet#1]
I've got some images in the media library that don't have categories and they default to "Uncategorised" if I use them anywhere.

The code to ignore this type when producing category lists in `page-how-do-i.php` is only looking for the US spelling "Uncategorized".

Simple fixes:

```
//first foreach loop:
if ($taxonomy->name == 'Uncategorised' || $taxonomy->name == 'Uncategorized') continue;
....
//2nd foreach loop:
if ($themeURL == 'uncategorised' || $themeURL == 'uncategorized') {
    continue;
}
```

A better fix would be to use an ACF option to create a list of Categories to ignore which would then enable images used in blog posts/news stories to still be categorised.

**Comment by nmcgann** [comment]
On further investigation I have found I have access to one Wordpress installation with "Uncategorised" and another with "Uncategorized". I think one must have had the UK spelling category created and set as default and the US spelling one deleted. Obscure!

The ACF "ignore" list would be a good solution as having hard-coded names is a bit suspect.

**Comment by lukeoatham** [comment]
Updated to check for term_id 1
