### ISSUE TITLE
HT Feature blogposts hyperlink

### ISSUE THREAD

**Issue by FredWBeck** [helpful/govintranet#22]
Can anyone confirm this on their GovIntranet 4.9.5.1 powered site?

On the homepage first column I am using the HT Feature blogposts widget to display 5 items, 365 days freshness, with excerpt, thumbnail, and link to more. I currently have one post that gets displayed in this widget.

Clicking the **thumbnail** of this post will correctly open the blog post, however clicking the **post title** in this widget only links back to the site's home page.

(Polylang plugin is installed for i18n in case this makes a difference)

**Comment by lukeoatham** [comment]
Okay in 4.9.6?

**Comment by FredWBeck** [comment]
Yes, this appears to be fixed now; tested in 4.9.6.1.
