### ISSUE TITLE
%htitle% in breadcrumb on staff directory profile page

### ISSUE THREAD

**Issue by tommarshall** [helpful/govintranet#27]
The staff directory page is displaying `%htitle%` instead of the home page as the root item of the breadcrumb.

![image](https://cloud.githubusercontent.com/assets/1125251/26300249/7eb22200-3ed5-11e7-9883-11d89a899657.png)

Present in govintranet 4.34.12, with bbpress 2.5.12 and breadcrumb-navxt 5.3.1 & 5.7.0.

**Comment by tommarshall** [comment]
This issue appears to have been introduced in [4.34.5](https://github.com/helpful/govintranet/commit/937b43441eaa783071fb5d007a74403563ed4fe1#diff-04653a3c8a4563eeb5c68e29cee29e0e).

**Comment by lukeoatham** [comment]
This was reported in the forums and we're waiting to get a fix released: https://help.govintra.net/topic/breadcrumb-problem-in-the-staff-directory/
