### ISSUE TITLE
Plugin dependency: Advanced Custom Fields

### ISSUE THREAD

**Issue by marcus-downing** [helpful/govintranet#9]
If the _Advanced Custom Fields_ plugin isn't switched on, the theme produces an unhelpful "white screen of death". It would be better if the theme detected the presence or absence of required plugins, and either skipped optional features or displayed a helpful error message.

https://github.com/helpful/govintranet/blob/master/govintranet/functions.php#L2557:

``` php
acf_add_local_field_group(array (
    'key' => 'group_53bd5ee07ca71',
    'title' => 'Intranet configuration',
    'fields' => array (
        array (
            ...
```

**Comment by marcus-downing** [comment]
Ahem. It turns out this is slightly more complicated than the issue I reported.

The theme _does_ in fact check for the presence of the _Advanced Custom Fields_ plugin; however, if it finds it then it calls functions that are only available in the paid version of the plugin. Since we only had the free version of the plugin installed, it failed.

This is still a bug in the theme, but a more subtle one since both versions of the plugin will identify themselves the same.

**Comment by martinwrightgithub** [comment]
I found the information on the missing `acf_add_local_field_group()` in the free version being discussed here. 

https://github.com/elliotcondon/acf/issues/412

**Comment by lukeoatham** [comment]
The theme is not designed to work with the free version of the ACF plugin - sorry. I don't bother checking because the theme won't work without the plugin. ACF Pro is not an optional feature.
